### ISSUE TITLE
Version 2 is linked from pursuit, but doesn't seem to be listed as "latest"

### ISSUE THREAD

**Issue by coltfred** [purescript-contrib/purescript-arraybuffer-types#7]
https://pursuit.purescript.org/packages/purescript-arraybuffer-types/2.0.0/docs/Data.ArrayBuffer.Types

Click any "source" link on that page and you'll get 404s.

**Comment by garyb** [comment]
That's weird, the links seem to point to totally the wrong place:

https://github.com/purescript-contrib/purescript-arraybuffer-types/blob/v2.0.0/src/purescript/purescript-arraybuffer-types/src/Data/ArrayBuffer/Types.purs#L4-L4

Rather than:

https://github.com/purescript-contrib/purescript-arraybuffer-types/blob/v2.0.0/src/Data/ArrayBuffer/Types.purs#L4-L4

**Comment by garyb** [comment]
I republished it and the links seem to be good now. Thanks for the note about it!
